openapi: 3.0.0
info:
  title: wallet web app
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/wallets/{walletName}':
    parameters:
      - schema:
          type: string
        name: walletName
        in: path
        required: true
    get:
      summary: get wallet info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wallet'
              examples: {}
      operationId: get-wallets-walletName
      description: get wallet object
  '/wallets/{walletName}/tokens':
    parameters:
      - schema:
          type: string
        name: walletName
        in: path
        required: true
    get:
      summary: get token list in wallet
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  tokens:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - capture_id
                        - capture_photo_url
                        - created_at
                        - planter_id
                        - planter_name
                        - planter_photo_url
                      properties:
                        id:
                          type: string
                          minLength: 1
                        capture_id:
                          type: string
                          minLength: 1
                        capture_photo_url:
                          type: string
                          minLength: 1
                        created_at:
                          type: string
                          minLength: 1
                        planter_id:
                          type: string
                          minLength: 1
                        planter_name:
                          type: string
                          minLength: 1
                        planter_photo_url:
                          type: string
                          minLength: 1
                required:
                  - tokens
                x-examples:
                  example-1:
                    tokens:
                      - id: c488301f-1117-48c3-8866-3c38f28d3f25
                        capture_id: '932758'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.42.48_-4.882362633999999_38.38042393_e930d565-e28c-4e28-a313-16c85df989f1_IMG_20210517_143630_167714448.jpg'
                        created_at: '5/17/2021, 7:36:18 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
                      - id: 951554de-145c-11ec-82a8-0242ac130003
                        capture_id: '933042'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
                        created_at: '5/18/2021, 5:14:48 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
              examples:
                example-1:
                  value:
                    tokens:
                      - id: c488301f-1117-48c3-8866-3c38f28d3f25
                        capture_id: '932758'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.42.48_-4.882362633999999_38.38042393_e930d565-e28c-4e28-a313-16c85df989f1_IMG_20210517_143630_167714448.jpg'
                        created_at: '5/17/2021, 7:36:18 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
                      - id: 951554de-145c-11ec-82a8-0242ac130003
                        capture_id: '933042'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
                        created_at: '5/18/2021, 5:14:48 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
      operationId: get-wallets-walletName-tokens
components:
  schemas:
    wallet:
      title: wallet
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        token_in_wallet:
          type: number
        photo_url:
          type: string
      x-examples:
        example-1:
          value:
            id: 4d96c4ca-1444-11ec-82a8-0242ac130003
            name: SustainablyRun
            token_in_wallet: 2
            photo_url: 'https://dadior.s3.ap-northeast-1.amazonaws.com/wallet-avatar.jpeg'
    token:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        capture_id:
          type: string
          minLength: 1
        capture_photo_url:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        planter_id:
          type: string
          minLength: 1
        planter_name:
          type: string
          minLength: 1
        planter_photo_url:
          type: string
          minLength: 1
      required:
        - id
        - capture_id
        - capture_photo_url
        - created_at
        - planter_id
        - planter_name
        - planter_photo_url
      x-examples: {}
